import random
class randomnumber:
    def randomone(list):
        count=1
        while(count<=6):
            rand=random.randint(1,6)
            list.append(rand)
            count+=1
        return list
    
    newlist=[]
    checklist=[]
    mylist=randomone(newlist)

    for x in mylist:
        print("data generated by random number ",x)
        if (x not in checklist):
            checklist.append(x)
    if(len(mylist)==len(checklist)):
        print("All data gets generated in random generator")

    for x in checklist:
        if(mylist.count(x)>1):
            print(x," Data repeated here ",mylist.count(x)," times")
    print(checklist)
